package RemotInterfaceApp;


/**
* RemotInterfaceApp/RemotInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLFile.idl
* Thursday, June 16, 2016 6:51:02 AM EDT
*/

abstract public class RemotInterfaceHelper
{
  private static String  _id = "IDL:RemotInterfaceApp/RemotInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, RemotInterfaceApp.RemotInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RemotInterfaceApp.RemotInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RemotInterfaceApp.RemotInterfaceHelper.id (), "RemotInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RemotInterfaceApp.RemotInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RemotInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RemotInterfaceApp.RemotInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RemotInterfaceApp.RemotInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemotInterfaceApp.RemotInterface)
      return (RemotInterfaceApp.RemotInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemotInterfaceApp._RemotInterfaceStub stub = new RemotInterfaceApp._RemotInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RemotInterfaceApp.RemotInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RemotInterfaceApp.RemotInterface)
      return (RemotInterfaceApp.RemotInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RemotInterfaceApp._RemotInterfaceStub stub = new RemotInterfaceApp._RemotInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
