package corbafiles;


/**
* RemotInterfaceApp/RemotInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLFile.idl
* Thursday, June 16, 2016 6:51:02 AM EDT
*/

public interface RemotInterface extends RemotInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RemotInterface
