package corbafiles;


/**
* RemotInterfaceApp/RemotInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDLFile.idl
* Thursday, June 16, 2016 6:51:02 AM EDT
*/

public interface RemotInterfaceOperations 
{
  String createDRecord (String managerId, String firstName, String lastName, String address, String phone, String specialization, String location);
  String createNRecord (String managerId, String firstName, String lastName, String designation, String status, String statusDate);
  String getRecordCount (String managerId, int recordType);
  String editRecord (String managerId, String recordID, String fieldName, String newValue);
  String transferRecord (String managerID, String recordID, String remoteClinicServerName);
} // interface RemotInterfaceOperations
